services:
  dash-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev 
    container_name: mi_app_desarrollo
    ports:
      - "8050:8050"
    volumes:
      - ./app:/app
      - /home/tehe/Work/tfm/datasets/ines/executions/executions:/app/executions
      # - ./files_output/:/output
      # - ./epoch_processed:/app/epoch_processed
      - ./files_output/queries:/app/output/
      - ./files_output/multi_requests_file.yml:/app/scripts/multi_requests_file.yml
      - ./components.yml:/app/components.yml
      - ./epoch_processed:/app/epoch_processed
    environment:
      DASH_DEBUG: "true"
      SERVER_PORT: "8060"
      WINDOW_VERSION: "${WINDOW_VERSION:-v001}"
      OBS_EVENTS_COLUMN: "OW_events"
      PRED_EVENTS_COLUMN: "PW_events"
      DATASET_PROCESSED_PATH: "/app/epoch_processed"
      DATASET_RAM_TIMEOUT: "10"
    command: uvicorn main:app --host 0.0.0.0 --port 8050 --reload
    
    # LIMITACIÓN DE RECURSOS
    deploy:
      resources:
        limits:
          memory: 8G     
          cpus: '2.0'    
        reservations:
          memory: 1G     
    restart: unless-stopped